### ISSUE TITLE
Usage Documentation Error for framework CLI option

### ISSUE THREAD

**Issue by pierre-ernst** [secdec/attack-surface-detector-cli#1]
the CLI allows to specify which framework to scan.

the documentation at
"https://github.com/secdec/attack-surface-detector-cli/wiki/Usage,-Parameters,-and-Output"
 
should have "-defaultFramework" instead of "-framework"

**Comment by matthewD-AVI** [comment]
@pierre-ernst Thank you for bringing this typo in our documentation to our attention. I have fixed this mistake and appreciate your contribution.
